[build]
command = "cargo install trunk && trunk build --release"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://rpeabs.net/cs2autoexec/:splat"
status = 301
force = true
